#publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate : 50

#Position Controllers
fly_wheel_joint_controller:
  type: effort_controllers/JointPositionController
  joint: fly_wheel_joint
  pid : {p: 2000.0, i: 100.0, d: 500.0}
wheel_joint_controller:
  type: effort_controllers/JointPositionController
  joint: wheel_joint
  pid: {p: 50000.0,i: 100.0, d: 2000.0}
  
